version: '3.8'

services:

  risk-db:
    image: postgres:15
    container_name: risk-db
    environment:
      POSTGRES_DB: risk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - risk-db-data:/var/lib/postgresql/data
      - ./init/risk-db.sql:/docker-entrypoint-initdb.d/risk-db.sql
    networks:
      - invest-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d risk_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  risk-db-data:

networks:
  invest-network:
    external: true