version: "3.8"

services:
  risk-postgres:
    image: postgres:15-alpine
    container_name: invest-risk-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=invest_risk_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - risk_postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  risk_postgres_data: